networks:
  local-net:
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=Lw9OqbTTThnj*pzx6m4X
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - local-net
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=Lw9OqbTTThnj*pzx6m4X
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - local-net
    ports:
      - "5000:5000"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Lw9OqbTTThnj*pzx6m4X
    networks:
      - local-net
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-net
    ports:
      - "127.0.0.1:9089:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - local-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    container_name: jaeger-collector
    ports:
      - "14250:14250"  # Jaeger gRPC port
      - "14268:14268"  # Jaeger HTTP port
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=Lw9OqbTTThnj*pzx6m4X
      - ES_TAG_KEYS_AS_FIELDS_ALL=true
      - ES_TEMPLATE_PRIORITY=100  # Set a higher priority for the Jaeger templates
    depends_on:
      - elasticsearch
    networks:
      - local-net


  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger-query
    ports:
      - "16686:16686"  # Jaeger Query UI port
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAG_KEYS_AS_FIELDS_ALL=true
      - ES_USERNAME=elastic
      - ES_PASSWORD=Lw9OqbTTThnj*pzx6m4X
    depends_on:
      - jaeger-collector
      - elasticsearch
    networks:
      - local-net

volumes:
  prometheus_data: { }
  esdata1:
    driver: local
